// Configuration header for external library dependencies.
//
// This header is auto-generated by CMake.  DO NOT TOUCH.

// std::tr1::unordered_map<>-related
/* #undef Boost_FOUND */
#define TR1_UNORDERED_MAP_FOUND 1
#define TR1_UNORDERED_MAP_USE_TR1_UNORDERED_MAP 1
/* #undef TR1_UNORDERED_MAP_USE_UNORDERED_MAP */

// Make the unordered map template available in the std::tr1 namespace.
#if TR1_UNORDERED_MAP_FOUND
  #if TR1_UNORDERED_MAP_USE_TR1_UNORDERED_MAP
    #include <tr1/unordered_map>
  #elif TR1_UNORDERED_MAP_USE_MEMORY && !TR1_UNORDERED_MAP_USE_TR1_UNORDERED_MAP
    #include <unordered_map>
    namespace std { namespace tr1 {
      using std::UNORDERED_MAP;
    } }
  #elif Boost_FOUND
    #include <boost/unordered_map.hpp>
    namespace std { namespace tr1 {
      using boost::UNORDERED_MAP;
    } }
  #else  // #if TR1_UNORDERED_MAP_USE_TR1_UNORDERED_MAP
    #error unordered_map implementation required for building test_synopsis!
  #endif  // #if TR1_UNORDERED_MAP_USE_TR1_UNORDERED_MAP
#endif  // #if TR1_UNORDERED_MAP_FOUND
